[pytest]
addopts =
  --deselect=python/transform/test_tilelang_transform_lower_tile_op.py
  --deselect=python/language/test_tilelang_language_get_warp_info.py
  --deselect=python/layout/test_tilelang_hierarchical_layout.py
  --ignore=python/tilelibrary
